enum EventTypes {
  ADD_VOTES,
  DETRACT_VOTES_FOR_OPTION,
  VOID_VOTES,
  INCREASE_NUMBER_DELEGATES_VOTED,
  DECREASE_NUMBER_DELEGATES_VOTED,
}
const INCREASE_NUMBER_DELEGATES_VOTED = 'INCREASE_NUMBER_DELEGATES_VOTED'
const DECREASE_NUMBER_DELEGATES_VOTED = 'DECREASE_NUMBER_DELEGATES_VOTED'
const VOID_VOTES = 'VOID_VOTES'
const ADD_VOTES = 'ADD_VOTES'
const DETRACT_VOTES_FOR_OPTION = 'DETRACT_VOTES_FOR_OPTION'
export increaseNumberDelegatesVotedAction = {
  type: INCREASE_NUMBER_DELEGATES_VOTED
}

export decreaseNumberDelegatesVotedAction = {
  type: DECREASE_NUMBER_DELEGATES_VOTED
}

export addVotesAction = {
  type: ADD_VOTES,
  optionId: 0,
  votes: []
}